# Generated by Django 4.2 on 2024-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heterogeneous_system_integrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformstep',
            name='discard_leftover_fields',
        ),
        migrations.AddField(
            model_name='transformstep',
            name='keep_leftover_fields',
            field=models.BooleanField(default=False, help_text='Behavior with the data fields that have not been mapped.'),
        ),
        migrations.AlterField(
            model_name='transformstep',
            name='conversions_after_mappings',
            field=models.BooleanField(default=False, help_text='Conversions change values over the specified field names. This process can be done on the original fields or the mapped fields.'),
        ),
    ]
