# Generated by Django 4.2 on 2024-05-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heterogeneous_system_integrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftpdatalocation',
            name='filename_or_regex_pattern',
        ),
        migrations.AddField(
            model_name='ftpdatalocation',
            name='filename',
            field=models.CharField(blank=True, help_text='Filename from where to get or where to save the data.', null=True),
        ),
        migrations.AddField(
            model_name='ftpdatalocation',
            name='regex_pattern',
            field=models.CharField(blank=True, help_text='Regular expression to get data from multiple files. Only compatible with download Transfer Steps.', null=True),
        ),
    ]
