# Generated by Django 4.2 on 2024-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heterogeneous_system_integrator', '0002_remove_ftpdatalocation_filename_or_regex_pattern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftpdatalocation',
            name='path_to_files',
        ),
        migrations.AddField(
            model_name='ftpdatalocation',
            name='directory_path',
            field=models.CharField(default='/', help_text='Path to the directory where the transfering file process is going to take place. Separate field names using slashes (/)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ftpdatalocation',
            name='filename',
            field=models.CharField(blank=True, help_text='Filename from where to get or where to save the data', null=True),
        ),
        migrations.AlterField(
            model_name='ftpdatalocation',
            name='regex_pattern',
            field=models.CharField(blank=True, help_text='Regular expression to get data from multiple files', null=True),
        ),
    ]
