from setuptools import setup, find_packages

setup(
   name='heterogeneous_system_integrator',
   author='Tiodor V.K.',
   author_email='TiodorVK@gmail.com',
   version='1.0',
   packages=find_packages(),
   install_requires=[
       'amqp~=5.2.0',
       'billiard~=4.2.0',
       'celery~=5.4.0',
       'cryptography~=42.0.5',
       'django-celery-beat~=2.6.0',
       'django-celery-beat~=2.6.0',
       'django-celery-results~=2.5.1',
       'django-celery-results~=2.5.1',
       'django-filter~=24.2',
       'django~=4.2',
       'djangorestframework~=3.15.1',
       'dnspython~=2.6.1',
       'eventlet~=0.36.1',
       'flower~=2.0.1',
       'flower~=2.0.1',
       'greenlet~=3.0.3',
       'kombu~=5.3.7',
       'markdown~=3.6',
       'psycopg2~=2.9.9',
       'requests~=2.31.0',
       'vine~=5.1.0',
   ],
)
